#cloud-config
users:
  - name: ubuntu
    plain_text_passwd: ubuntu
    lock_passwd: false
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL'] # khong can nhap pass khi dung sudo 
package_update: true
package_upgrade: true
packages:
  - nginx
  - git
  - curl
runcmd:
  - [touch, /tmp/testfile.txt]