#cloud-config
packages:
  - net-tools

users:
  - name: ubuntu
    plain_text_passwd: ubuntu
    lock_passwd: false
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

runcmd:
  - echo "Xin chao! ifconfig da san sang su dung" > /tmp/hello.txt
  - ifconfig > /tmp/network-info.txt